version: "3.9"

services:
  mysql:
    image: mysql:8.0
    command:
      - --bind-address=0.0.0.0
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    container_name: mysql_loja
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: loja_roupas
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - loja-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      interval: 5s
      retries: 10

  mongo:
    image: mongo:6
    container_name: mongo_loja
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/seed.js:/docker-entrypoint-initdb.d/seed.js
    networks:
      - loja-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      timeout: 20s
      interval: 5s
      retries: 10

  etl:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: etl_loja
    tty: true
    stdin_open: true
    depends_on:
      mysql:
        condition: service_healthy
      mongo:
        condition: service_healthy
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_HOST: mysql
      MONGODB_URI: mongodb://mongo:27017/
    networks:
      - loja-network
    volumes:
      - .:/app
    command: tail -f /dev/null
    healthcheck:
      test: ["CMD", "python", "-c", "import mysql.connector; import pymongo"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  loja-network:
    driver: bridge
